### ISSUE TITLE
How to get the actual download links 

### ISSUE THREAD

**Issue by TheAbhijeet** [apoorvaeternity/Youtube-Video-Downloader#3]
Hey, How to get the actual download links of the files, the script is great but it is playing the files in the browser instead of downloading it.

**Comment by apoorvaeternity** [comment]
Hey - @TheAbhijeet - that's an issue with some links as I am not serving the video from the django server itself but directly from YouTube servers. The other alternative is to right click on the link and click "Save link as..." option to save the video.
